import { ticket } from "fontawesome";

export const data = [
  {

    id: 1,
    image: "packages/logo.jpg",
    package: 'day17.JPG',
    name: "06 Days Kumrat valley Trip",
    departure: "Islamabad, Pakistan",
    description: "At TravelNMemories, we don’t just plan trips — we create memories. Each of our tour packages is crafted with care, offering seamless planning, personalized service, and the comfort you deserve. Whether you're looking for a quick getaway or a grand adventure, we're here to make your journey unforgettable. Book your next trip with us — because every journey tells a story, and every story deserves to be memorable.",
    rating: 5,
    reviews: 3,
    days: '06',
    location : 'https://maps.app.goo.gl/fJsZwqMNSvrpn4yx6<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12986.72003586977!2d72.20900820645268!3d35.53690452140169!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38dc96b3fd4980dd%3A0x3820c0856f118ef3!2sKumrat%20Valley!5e0!3m2!1sen!2s!4v1744708657343!5m2!1sen!2s',
    destination: "Kumrat valley",
    tickets: 'Not Included',
    car : 'Toyota Corolla',
    Group_tour: "24000 PKR",
    couple: "50000 PKR",
    package_cost : '180,000 PKR',
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: 'Not Included',
    plan: [
      {
        question: 'Day 1 Pickup from Islamabad', answer: " Pick up from Islamabad & Departure for Kalam : Swat Expressway, Fiza Ghat, Mingora, Madian, Bahrain Stay: Kalam", },
      { question: 'Day 2 Departure for kamrat', answer: "Departure for kamrat valley jeep track sightseeing Blue water kamrat waterfall Stay kamrat", },
      { question: 'Day 3 Departure for jahaz', answer: "Departure for jahaz Panda sightseeing track Kala chashma Stay kamrat", },
      { question: 'Day 4 Departure for kalam', answer: "Departure for kalam local sightseeing Stay kalam", },
      { question: 'Day 5 Departure for  Malam Jabba', answer: "Departure for Malam Jabba Sightseeing: Chairlift, Zipline Stay: Malam Jabba", },
      { question: 'Day 6 Back to Islamabad', answer: "Back to Islamabad & Drop.", },
    ],
  },
  {
    id: 2,
    image: "packages/06hunza.png",
    package: '06hunza.png',
    name: "06 Days Hunza Trip",
    departure: "Islamabad, Pakistan",
    description: "At TravelNMemories, we don’t just plan trips — we create memories. Each of our tour packages is crafted with care, offering seamless planning, personalized service, and the comfort you deserve. Whether you're looking for a quick getaway or a grand adventure, we're here to make your journey unforgettable. Book your next trip with us — because every journey tells a story, and every story deserves to be memorable.",
    rating: 5,
    reviews: 3,
    days: '06',
    location : 'https://maps.app.goo.gl/fJsZwqMNSvrpn4yx6<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12986.72003586977!2d72.20900820645268!3d35.53690452140169!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38dc96b3fd4980dd%3A0x3820c0856f118ef3!2sKumrat%20Valley!5e0!3m2!1sen!2s!4v1744708657343!5m2!1sen!2s',
    destination: "Hunza",
    Inclusive: 'Deluxe (02 Adults)',
    tickets: 'Not Included',
    car : 'Toyota Corolla Gli',
    Group_tour: "19500 PKR",
    couple: "42000 PKR",
    package_cost : '160,000 PKR',
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: 'Not Included',
    plan: [
      { question: 'Day 1 Pickup from Islamabad', answer: "Pickup from Islamabad & Departure for Balakot Sightseeing: Hazara Expressway, Mansehra, Balakot City, Kunar River kagan Stay: Naran", },
      { question: 'Day 2 Departure for Hunza', answer: "Departure for Hunza sightseeing nanga parvlbat 3 mountain junction gilgit stay Hunza", },
      { question: 'Day 3 Departure for Khunjerab Pass', answer: "Departure for Khunjerab Pass Sightseeing: Hussaini Bridge, Passu Cones, Passu Glacier, Sost Stay: Hunza", },
      { question: 'Day 4 Departure for Gilgit', answer: " Departure for gilgit Sightseeing: altit fort baltit fort Mina pen Stay: gilgit", },
      { question: 'Day 5 Departure for  kagan', answer: "departure for kagan  Stay kagan", },
      { question: 'Day 6 Back to Islamabad', answer: "Back to Islamabad & Drop", },
    ],
  },
  {

    id: 3,
    image: "packages/logo.jpg",
    package: 'day17.JPG',
    name: "Hunza and gilgit Trip",
    departure: "Islamabad, Pakistan",
    description: "At TravelNMemories, we don’t just plan trips — we create memories. Each of our tour packages is crafted with care, offering seamless planning, personalized service, and the comfort you deserve. Whether you're looking for a quick getaway or a grand adventure, we're here to make your journey unforgettable. Book your next trip with us — because every journey tells a story, and every story deserves to be memorable.",
    rating: 5,
    reviews: 3,
    days: '07',
    location : 'https://maps.app.goo.gl/fJsZwqMNSvrpn4yx6<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12986.72003586977!2d72.20900820645268!3d35.53690452140169!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38dc96b3fd4980dd%3A0x3820c0856f118ef3!2sKumrat%20Valley!5e0!3m2!1sen!2s!4v1744708657343!5m2!1sen!2s',
    destination: "Hunza",
    tickets: 'Not Included',
    jeep : 'Included',
    car : 'Toyota Corolla Gli',
    Group_tour: "27500 PKR",
    couple: "50000 PKR",
    package_cost : '195,000 PKR',
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: 'Not Included',
    plan: [
      {
        question: 'Day 1 Pickup from Islamabad', answer: " Pick up from Islamabad & Departure for Chilas sightseeing : Hunza Expressway, Besham, Basu Dam stay : Chilas", },
      { question: 'Day 2 Departure for Hunza', answer: "Departure for Hunza sightseeing : Nanga Parbat, Gilgit Raka Poshi View Point Stay : Hunza", },
      { question: 'Day 3 Departure for Khunjerab Pass', answer: "Departure for Khunjerab Pass sightseeing Attabad lake, Hussani Bridge, Passu Cones, Sost Border stay: Attabad Lake", },
      { question: 'Day 4 Departure for Hunza', answer: "Departure for Hunza Karimabad sightseeing: Altit & ıaltit Fort, Eagle Nest stay : Hunza", },
      { question: 'Day 5 Departure for  Gligit', answer: "Departure for Gligit (Jeep Track Naltar Valley) Sightseeing : Safranga Lake, Zero Point, Snow Leopard stay: Gligit", },
      { question: 'Day 6 Departure for Besham', answer: "Departure for Besham stay : Besham", },
      { question: 'Day 7 Back to Islamabad', answer: "Back to Islamabad & Drop.", },
    ],
  },
  {
    id: 4,
    image: "packages/06skardu.png",
    name: "06 Day skardu Trip",
    departure: "Islamabad, Pakistan",
    description: "At TravelNMemories, we don’t just plan trips — we create memories. Each of our tour packages is crafted with care, offering seamless planning, personalized service, and the comfort you deserve. Whether you're looking for a quick getaway or a grand adventure, we're here to make your journey unforgettable. Book your next trip with us — because every journey tells a story, and every story deserves to be memorable.",
    rating: 5,
    Inclusive: 'Deluxe (02 Adults 2 children)',
    reviews: 3,
    days: '08',
    location : 'https://maps.app.goo.gl/fJsZwqMNSvrpn4yx6<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12986.72003586977!2d72.20900820645268!3d35.53690452140169!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38dc96b3fd4980dd%3A0x3820c0856f118ef3!2sKumrat%20Valley!5e0!3m2!1sen!2s!4v1744708657343!5m2!1sen!2s',
    destination: "skardu",
    tickets: 'Not Included',
    car : 'Toyota Corolla GLI',
    jeep : 'Included',
    package_cost : '160,000 PKR',
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: 'Breakfast',
    plan: [
      { question: 'Day 1 Pickup from Islamabad', answer: "Pickup from Islamabad & Departure for Naran Sightseeing: Hazara Expressway, Mansehra, Balakot City, Kunar River kagan Stay: Naran", },
      { question: 'Day 2 Departure for skardu', answer: "Departure for skardu Sightseeing:  Batakundi, Babusar Top nanga parbat three mountain junction lor kachura upper kachura Stay: skardu ", },
      { question: 'Day 3 Departure for Mantokha waterfall', answer: "Departure for  Mantokha waterfall cold desert Shigar Stay skardu", },
      { question: 'Day 4 Back to batta kundi', answer: " back to batta kundi Stay batta kundi", },
      { question: 'Day 5 Departure for shogra', answer: "Departure for shogra Sighteeing shogra national park", },
      { question: 'Day 6 Back to Islamabad', answer: "Back to Islamabad & Drop", },
    ],
  },
  {
    id: 5,
    image: "packages/08dayshs.png",
    name: "Hunza skardu Trip",
    departure: "Islamabad, Pakistan",
    description: "At TravelNMemories, we don’t just plan trips — we create memories. Each of our tour packages is crafted with care, offering seamless planning, personalized service, and the comfort you deserve. Whether you're looking for a quick getaway or a grand adventure, we're here to make your journey unforgettable. Book your next trip with us — because every journey tells a story, and every story deserves to be memorable.",
    rating: 5,
    Inclusive: 'Deluxe (02 Adults 2 children)',
    reviews: 3,
    days: '08',
    location : 'https://maps.app.goo.gl/fJsZwqMNSvrpn4yx6<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12986.72003586977!2d72.20900820645268!3d35.53690452140169!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38dc96b3fd4980dd%3A0x3820c0856f118ef3!2sKumrat%20Valley!5e0!3m2!1sen!2s!4v1744708657343!5m2!1sen!2s',
    destination: "skardu",
    tickets: 'Not Included',
    car : 'Toyota Corolla GLI',
    jeep : 'Included',
    Group_tour: "35000 PKR",
    couple: "50000 PKR",
    package_cost : '295,000 PKR',
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: 'Breakfast',
    plan: [
      { question: 'Day 1 Pickup from Islamabad', answer: "Pickup from Islamabad & Departure for Naran Sightseeing: Hazara Expressway, Mansehra, Balakot City, Kunar River kagan Stay: Naran", },
      { question: 'Day 2 Departure for Hunza', answer: "Departure for hunza Sightseeing: Kiwai Waterfall,  Naran, Kaghan, Batakundi, Babusar Top nanga parbat three mountain junction Stay: Hunza", },
      { question: 'Day 3 Departure for Khunjerab Pass', answer: "Departure for Khunjerab Pass Sightseeing: Hussaini Bridge, Passu Cones, Passu Glacier, Sost Stay: Hunza", },
      { question: 'Day 4 Departure for Skardu', answer: " Departure for Skardu Sighteeing lower kachura upper kachura Stay: skardu", },
      { question: 'Day 5 Departure for Mantokha waterfall', answer: "Departure for  Mantokha waterfall cold desert Shigar Stay skardu", },
      { question: 'Day 6 Back to batta', answer: "back to batta kundi Stay batta kundi ", },
      { question: 'Day 7 Back to Shogran', answer: "Departure for shogran Sighteeing shogran national Park shogran top Stay:shogran ", },
      { question: 'Day 8 Back to Islamabad', answer: "Back to Islamabad & Drop", },
    ],
  },
];
