export const data = [
    {
        id: 1,
        image: "banner2.jpg",
        package : 'day17.JPG',
        name: "Hajj 17 Days",
        description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        rating: 5,
        reviews: 3,
        days: '17',
        maktab: 'B',
        airline: "In-Direct",
        sharing_price: '6,370 USD',
        triple_bed_price: "6,460 USD",
        double_bed_price: "6,640 USD",
        payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
        food_included: 'Madinah ( Half Board ), Azizia ( Breakfast, Lunch, Dinner), Mina (3 meals provided by Saudi company)',
        features: [
          "Meet & assist upon arrival at Jeddah Airport",
          "Complete accommodation at Madinah, Azizia as mentioned",
          "Airfare included in above package through any indirect airline",
          "Ziarat Makkah & Madinah",
          "Seat-by-seat transport (Luxury Air-conditioned Busses)",
          "Maktab services as per Saudi company",
        ],
        note: [
          "Expats in the USA, Canada, UK, Europe, etc. will have different prices based on their countries.",
          "Azizia rooms on a sharing basis",
          "Qurbani not included",
          "Stay in Azizia & Madinah can decrease or increase subject to availability.",
        ],
      },
    {
        id: 2,
        image: "banner2.jpg",
        name: "Hajj 17 Days",
        package : 'day17.JPG',
        description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        days: '15',
        maktab: 'B',
        airline: "In-Direct",
        sharing_price: '6,370 USD',
        triple_bed_price: "6,460 USD",
        double_bed_price: "6,640 USD",
        payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
        food_included: 'Madinah ( Half Board ) , Azizia ( Breakfast , Lunch Dinner) , Mina 03 time meals provide by saudi company',
        features: [
            "Meet & assist upon arrival at Jeddah Airport",
            "Complete accommodation at Madinah & madinah & Azizia as mentioned",
            "Air fare included in above package through any indirect airline",
            "Ziarat Makkah & Madinah",
            "Seat ny seat transport ( Luxury AirCondition Busses )",
            "Maktab services as per saudi company",
        ],
        note: [
            "Expats in the USA, Canada , UK , Europe , Australia , Middle East , Far East , etc Will have different prices  based on their countries. If the ticket is purchased by yourself you can reduce USD 1100 from the above package cost ",
            "Azizia rooms on sharing basis",
            "Qurbani not included",
            "stay in Azizia & Madinah can be decrease of increase subject to available of seats",
        ],
    },
    {
        id: 3,
        image: "banner2.jpg",
        name: "Hajj 21 Days",
        package : 'day21.JPG',
        description: "A well-planned 21-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        days: '21',
        maktab: 'B',
        airline: "In-Direct",
        sharing_price: '6,810 USD',
        triple_bed_price: "6,900 USD",
        double_bed_price: "7,250 USD",
        payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
        food_included: 'Madinah ( Half Board ) , Azizia ( Breakfast , Lunch Dinner) , Mina 03 time meals provide by saudi company',
        features: [
            "Meet & assist upon arrival at Jeddah Airport",
            "Complete accommodation at Madinah & madinah & Azizia as mentioned",
            "Air fare included in above package through any indirect airline",
            "Ziarat Makkah & Madinah",
            "Seat ny seat transport ( Luxury AirCondition Busses )",
            "Maktab services as per saudi company",
        ],
        note: [
            "Expats in the USA, Canada , UK , Europe , Australia , Middle East , Far East , etc Will have different prices  based on their countries. If the ticket is purchased by yourself you can reduce USD 1100 from the above package cost ",
            "Azizia rooms on sharing basis",
            "Qurbani not included",
            "stay in Azizia & Madinah can be decrease of increase subject to available of seats",
        ],
    },
    {
        id: 4,
        image: "banner2.jpg",
        name: "Hajj 27 Days",
        package : 'day27.JPG',
        description: "A well-planned 27-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        days : '25',
        maktab : 'B',
        airline : "In-Direct",
        sharing_price : '7,700 USD',
        triple_bed_price : "8,050 USD",
        double_bed_price : "8,760 USD",
        payment_schedule : '100% payment advance at the time of booking ( Non refundable )',
        food_included : 'Madinah ( Half Board ) , Azizia ( Breakfast , Lunch Dinner) , Mina 03 time meals provide by saudi company',
        features: [
          "Meet & assist upon arrival at Jeddah Airport",
          "Complete accommodation at Madinah & madinah & Azizia as mentioned",
          "Air fare included in above package through any indirect airline",
          "Ziarat Makkah & Madinah",
          "Seat ny seat transport ( Luxury AirCondition Busses )",
          "Maktab services as per saudi company",
        ],
        note: [
          "Expats in the USA, Canada , UK , Europe , Australia , Middle East , Far East , etc Will have different prices  based on their countries. If the ticket is purchased by yourself you can reduce USD 1100 from the above package cost ",
          "Azizia rooms on sharing basis",
          "Qurbani not included",
          "stay in Azizia & Madinah can be decrease of increase subject to available of seats",
        ],
      },
      {
        id: 5,
        image: "banner2.jpg",
        name: "Hajj 17 Days",
        package : 'day172.JPG',
        description: "A well-planned 15-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        days : '15',
        maktab : 'B',
        airline : "In-Direct",
        sharing_price : '6,280 USD',
        triple_bed_price : "6,370 USD",
        double_bed_price : "6,550 USD",
        payment_schedule : '100% payment advance at the time of booking ( Non refundable )',
        food_included : 'Madinah ( Half Board ) , Azizia ( Breakfast , Lunch Dinner) , Mina 03 time meals provide by saudi company',
        features: [
          "Meet & assist upon arrival at Jeddah Airport",
          "Complete accommodation at Madinah & madinah & Azizia as mentioned",
          "Air fare included in above package through any indirect airline",
          "Ziarat Makkah & Madinah",
          "Seat ny seat transport ( Luxury AirCondition Busses )",
          "Maktab services as per saudi company",
        ],
        note: [
          "Expats in the USA, Canada , UK , Europe , Australia , Middle East , Far East , etc Will have different prices  based on their countries. If the ticket is purchased by yourself you can reduce USD 1100 from the above package cost ",
          "Azizia rooms on sharing basis",
          "Qurbani not included",
          "stay in Azizia & Madinah can be decrease of increase subject to available of seats",
        ],
      },
];

