import { ticket } from "fontawesome";

export const data = [
  {

    id: 1,
    image: "banner2.jpg",
    package: 'day17.JPG',
    name: "Sawaat Tour",
    departure: "Islamabad, Pakistan",
    description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat. A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat. A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
    rating: 5,
    reviews: 3,
    days: '17',
    destination: "Sawaat",
    tickets: 'Not Included',
    sharing_price: '6,370 USD',
    triple_bed_price: "6,460 USD",
    double_bed_price: "6,640 USD",
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: '( Breakfast , Lunch Dinner)',
    plan: [
      { question: 'Day 1 Pickup from Islamabad', answer: "Pickup from Islamabad & Departure for Balakot Sightseeing: Hazara Expressway, Mansehra, Balakot City, Kunar River kagan Stay: Naran", },
      { question: 'Day 2 Departure for Hunza', answer: "departure for Hunza sightseeing nanga parvlbat 3 mountain junction gilgit  stay Hunza", },
      { question: 'Day 3 Departure for Khunjerab', answer: "Departure for Khunjerab Pass Sightseeing: Hussaini Bridge, Passu Cones, Passu Glacier, Sost Stay: Hunza", },
      { question: 'Day 4 Departure for gilgit', answer: "Departure for gilgit Sightseeing: altit fort baltit fort Mina pen Stay: gilgit", },
      { question: 'Day 5 Departure for  kagan', answer: "departure for  kagan Stay kagan", },
    ],
  },
  {
    id: 2,
    image: "banner2.jpg",
    name: "Hajj 17 Days",
    package: 'day17.JPG',
    destination: "Sawaat",
    departure: "Islamabad, Pakistan",
    description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
    days: '15',
    sharing_price: '6,370 USD',
    triple_bed_price: "6,460 USD",
    double_bed_price: "6,640 USD",
    tickets: 'Not Included',
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: '( Breakfast , Lunch Dinner)',
    features: [
      "Meet & assist upon arrival at Jeddah Airport",
      "Complete accommodation at Madinah & madinah & Azizia as mentioned",
      "Air fare included in above package through any indirect airline",
      "Ziarat Makkah & Madinah",
      "Seat ny seat transport ( Luxury AirCondition Busses )",
      "Maktab services as per saudi company",
    ],
    plan: [
      { question: 'Day 2', answer: "Departure from Islamabad, Arrival in Madinah, Hotel check-in, Rest and free time for prayers.", },
      { question: 'Day 2', answer: "Visit Masjid al-Nabawi, Ziarat of important Islamic historical sites in Madinah.", },
      { question: 'Day 3', answer: "Free day in Madinah for individual ibadah and shopping.", },
    ],
    note: [
      "Expats in the USA, Canada , UK , Europe , Australia , Middle East , Far East , etc Will have different prices  based on their countries. If the ticket is purchased by yourself you can reduce USD 1100 from the above package cost ",
      "Azizia rooms on sharing basis",
      "Qurbani not included",
      "stay in Azizia & Madinah can be decrease of increase subject to available of seats",
    ],
  },
  {
    id: 3,
    image: "banner2.jpg",
    name: "Kashmir Tour",
    package: 'day21.JPG',
    destination: "Sawaat",
    departure: "Islamabad, Pakistan",
    description: "A well-planned 21-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
    days: '21',
    tickets: 'Not Included',
    sharing_price: '6,810 USD',
    triple_bed_price: "6,900 USD",
    double_bed_price: "7,250 USD",
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: '( Breakfast , Lunch Dinner)',
    plan: [
      { questionquestion: 'Day 2', answer: "Departure from Islamabad, Arrival in Madinah, Hotel check-in, Rest and free time for prayers.", },
      { question: 'Day 2', answer: "Visit Masjid al-Nabawi, Ziarat of important Islamic historical sites in Madinah.", },
      { question: 'Day 3', answer: "Free day in Madinah for individual ibadah and shopping.", },
    ],
  },
  {
    id: 4,
    image: "banner2.jpg",
    name: "Hunza 7 Days Tour",
    package: 'day27.JPG',
    destination: "Sawaat",
    departure: "Islamabad, Pakistan",
    description: "A well-planned 27-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
    days: '25',
    maktab: 'B',
    tickets: 'Not Included',
    sharing_price: '7,700 USD',
    triple_bed_price: "8,050 USD",
    double_bed_price: "8,760 USD",
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: '( Breakfast , Lunch Dinner)',
    plan: [
      { question: 'Day 2', answer: "Departure from Islamabad, Arrival in Madinah, Hotel check-in, Rest and free time for prayers.", },
      { question: 'Day 2', answer: "Visit Masjid al-Nabawi, Ziarat of important Islamic historical sites in Madinah.", },
      { question: 'Day 3', answer: "Free day in Madinah for individual ibadah and shopping.", },
    ],
  },


  {
    id: 5,
    image: "banner2.jpg",
    package: 'day17.JPG',
    name: "Sawaat Tour",
    departure: "Islamabad, Pakistan",
    description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat. A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat. A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
    rating: 5,
    reviews: 3,
    days: '17',
    destination: "Sawaat",
    tickets: 'Not Included',
    sharing_price: '6,370 USD',
    triple_bed_price: "6,460 USD",
    double_bed_price: "6,640 USD",
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: '( Breakfast , Lunch Dinner)',
    plan: [
      { question: 'Day 1 Pickup from Islamabad', answer: "Pickup from Islamabad & Departure for Balakot Sightseeing: Hazara Expressway, Mansehra, Balakot City, Kunar River kagan Stay: Naran", },
      { question: 'Day 2 Departure for Hunza', answer: "departure for Hunza sightseeing nanga parvlbat 3 mountain junction gilgit  stay Hunza", },
      { question: 'Day 3 Departure for Khunjerab', answer: "Departure for Khunjerab Pass Sightseeing: Hussaini Bridge, Passu Cones, Passu Glacier, Sost Stay: Hunza", },
      { question: 'Day 4 Departure for gilgit', answer: "Departure for gilgit Sightseeing: altit fort baltit fort Mina pen Stay: gilgit", },
      { question: 'Day 5 Departure for  kagan', answer: "departure for  kagan Stay kagan", },
    ],
  },
  {
    id: 6,
    image: "banner2.jpg",
    package: 'day17.JPG',
    name: "Sawaat Tour",
    departure: "Islamabad, Pakistan",
    description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat. A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat. A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
    rating: 5,
    reviews: 3,
    days: '17',
    destination: "Sawaat",
    tickets: 'Not Included',
    sharing_price: '6,370 USD',
    triple_bed_price: "6,460 USD",
    double_bed_price: "6,640 USD",
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: '( Breakfast , Lunch Dinner)',
    plan: [
      { question: 'Day 1 Pickup from Islamabad', answer: "Pickup from Islamabad & Departure for Balakot Sightseeing: Hazara Expressway, Mansehra, Balakot City, Kunar River kagan Stay: Naran", },
      { question: 'Day 2 Departure for Hunza', answer: "departure for Hunza sightseeing nanga parvlbat 3 mountain junction gilgit  stay Hunza", },
      { question: 'Day 3 Departure for Khunjerab', answer: "Departure for Khunjerab Pass Sightseeing: Hussaini Bridge, Passu Cones, Passu Glacier, Sost Stay: Hunza", },
      { question: 'Day 4 Departure for gilgit', answer: "Departure for gilgit Sightseeing: altit fort baltit fort Mina pen Stay: gilgit", },
      { question: 'Day 5 Departure for  kagan', answer: "departure for  kagan Stay kagan", },
    ],
  },
  {
    id: 7,
    image: "banner2.jpg",
    package: 'day17.JPG',
    name: "Sawaat Tour",
    departure: "Islamabad, Pakistan",
    description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat. A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat. A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
    rating: 5,
    reviews: 3,
    days: '17',
    destination: "Sawaat",
    tickets: 'Not Included',
    sharing_price: '6,370 USD',
    triple_bed_price: "6,460 USD",
    double_bed_price: "6,640 USD",
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: '( Breakfast , Lunch Dinner)',
    plan: [
      { question: 'Day 1 Pickup from Islamabad', answer: "Pickup from Islamabad & Departure for Balakot Sightseeing: Hazara Expressway, Mansehra, Balakot City, Kunar River kagan Stay: Naran", },
      { question: 'Day 2 Departure for Hunza', answer: "departure for Hunza sightseeing nanga parvlbat 3 mountain junction gilgit  stay Hunza", },
      { question: 'Day 3 Departure for Khunjerab', answer: "Departure for Khunjerab Pass Sightseeing: Hussaini Bridge, Passu Cones, Passu Glacier, Sost Stay: Hunza", },
      { question: 'Day 4 Departure for gilgit', answer: "Departure for gilgit Sightseeing: altit fort baltit fort Mina pen Stay: gilgit", },
      { question: 'Day 5 Departure for  kagan', answer: "departure for  kagan Stay kagan", },
    ],
  },
  {
    id: 8,
    image: "banner2.jpg",
    name: "Hajj 17 Days",
    destination: "Sawaat",
    departure: "Islamabad, Pakistan",
    package: 'day172.JPG',
    description: "A well-planned 15-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
    days: '15',
    maktab: 'B',
    tickets: 'Not Included',
    sharing_price: '6,280 USD',
    triple_bed_price: "6,370 USD",
    double_bed_price: "6,550 USD",
    payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
    food_included: '( Breakfast , Lunch Dinner)',
    plan: [
      { question: 'Day 2', answer: "Departure from Islamabad, Arrival in Madinah, Hotel check-in, Rest and free time for prayers.", },
      { question: 'Day 2', answer: "Visit Masjid al-Nabawi, Ziarat of important Islamic historical sites in Madinah.", },
      { question: 'Day 3', answer: "Free day in Madinah for individual ibadah and shopping.", },
    ],
  },
];

